apiVersion: batch/v1
kind: CronJob
metadata:
  name: deployment-flipper-cronjob # updated this from code
spec:
  schedule: "* * * * *" # updated this from code
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: curl-container
            image: curlimages/curl
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - curl https://www.google.com # update this from code
          restartPolicy: OnFailure