apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-realworld
  labels:
    app: angular-realworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-realworld
  template:
    metadata:
      name: angular-realworld
      labels:
        app: angular-realworld
    spec:
      containers:
        - name: angular-realworld
          image: gothinkster/angular-realworld-example-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
      