apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-nginx-frontend
  labels:
    app: mesh
  namespace: service-mesh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-nginx-frontend
  template:
    metadata:
      name: react-nginx-frontend
      labels:
        app: react-nginx-frontend
    spec:
      containers:
        - name: react-nginx-frontend
          image: neroxxpips/react-nginx_frontend:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
      