apiVersion: v1
kind: Service
metadata:
  name: angular-realworld-app-service
spec:
  selector:
    app: angular-realworld
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30004
  type: NodePort
  