apiVersion: v1
kind: Service
metadata:
  name: jekyll-site-service
spec:
  selector:
    app: jekyll-site
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30005
  type: NodePort
  