apiVersion: v1
kind: Service
metadata:
  name: react-nginx-frontend
  namespace: service-mesh
spec:
  selector:
    app: react-nginx-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30003
  type: NodePort
  