apiVersion: v1
kind: Service
metadata:
  name: react-photo-feed-service
spec:
  selector:
    app: react-photo-feed
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30003
  type: NodePort
  