apiVersion: v1
kind: Service
metadata:
  name: static-site-service
spec:
  selector:
    app: static-site-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 3001
  type: NodePort
  