apiVersion: v1
kind: Service
metadata:
  name: vuejs-app-service
spec:
  selector:
    app: vuejs-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30002
  type: NodePort
  